<a href="https://colab.research.google.com/github/KimGriezmann/Bigcontest_2021/blob/master/working_space_SeongGwan/BigContest_final_df_create.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt 
import datetime


plt.rc('font', family='NanumBarunGothic')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
def create_df():

  #연도별 데이터 경로
  HTS_dir = '/content/drive/MyDrive/빅콘테스트/01_제공데이터/2021 빅콘테스트_데이터분석분야_챔피언리그_스포츠테크_HTS'
  Player_dir = '/content/drive/MyDrive/빅콘테스트/01_제공데이터/2021 빅콘테스트_데이터분석분야_챔피언리그_스포츠테크_선수'
  Hitter_dir = '/content/drive/MyDrive/빅콘테스트/01_제공데이터/2021 빅콘테스트_데이터분석분야_챔피언리그_스포츠테크_타자 기본'
  #단일 데이터 경로
  Team_dir = '/content/drive/MyDrive/빅콘테스트/01_제공데이터/2021 빅콘테스트_데이터분석분야_챔피언리그_스포츠테크_팀.csv'
  Schedule_dir = '/content/drive/MyDrive/빅콘테스트/01_제공데이터/2021 빅콘테스트_데이터분석분야_챔피언리그_스포츠테크_경기일정_2021.csv'
  val_dir = '/content/drive/MyDrive/빅콘테스트/02_평가데이터/2021 빅콘테스트_데이터분석분야_챔피언리그_스포츠테크_평가데이터.xlsx'

  year = [2018, 2019, 2020, 2021]

  for i in year:
    globals()['HTS_{}'.format(i)]     = pd.read_csv(HTS_dir + '_' + str(i) + '.csv', encoding='CP949')
    globals()['Player_{}'.format(i)]  = pd.read_csv(Player_dir + '_' + str(i) + '.csv', encoding='CP949')
    globals()['Hitter_{}'.format(i)]  = pd.read_csv(Hitter_dir + '_' + str(i) + '.csv', encoding='CP949')

  global Team_df, Schedule_df, val_df
  Team_df = pd.read_csv(Team_dir, encoding='CP949')
  Schedule_df = pd.read_csv(Schedule_dir, encoding='CP949')
  val_df = pd.read_excel(val_dir)

######################

#연도별 데이터 하나로 통합
def concat_df():
  df_list = ['HTS', 'Player', 'Hitter']

#각 칼럼이 모두 같은지 검사 후 통합
  for i in df_list:
    if ((globals()['{}_2018'.format(i)].columns == globals()['{}_2019'.format(i)].columns).all()) and ((globals()['{}_2019'.format(i)].columns == globals()['{}_2020'.format(i)].columns).all()) and \
    ((globals()['{}_2020'.format(i)].columns == globals()['{}_2021'.format(i)].columns).all()):
      globals()['{}_df'.format(i)] = pd.concat( [ globals()['{}_2018'.format(i)], globals()['{}_2019'.format(i)], globals()['{}_2020'.format(i)], globals()['{}_2021'.format(i) ] ] )

#연도별 길이의 합이 통합된 데이터의 길이와 같은지 검사
  for i in df_list:
    if len(globals()['{}_2018'.format(i)]) + len(globals()['{}_2019'.format(i)]) + len(globals()['{}_2020'.format(i)]) + len(globals()['{}_2021'.format(i)]) == len(globals()['{}_df'.format(i)]):
      print('{} is complete!'.format(i))

######################

create_df()
concat_df()

HTS is complete!
Player is complete!
Hitter is complete!

In [158]:
df_2018 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/add_hts_2018.csv', encoding='CP949')
df_2019 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/add_hts_2019.csv', encoding='CP949')
df_2020 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/add_hts_2020.csv', encoding='CP949')
df_2021 = pd.read_csv('/content/drive/MyDrive/빅콘테스트/add_hts_2021.csv', encoding='CP949')

In [159]:
# 분할 함수
def order(df, period, interval, del_cri, except_print):

    first_date = df.sort_values('DATE').reset_index(drop=True).loc[0,'DATE']

    last_date = df.sort_values('DATE').reset_index(drop=True).loc[len(df)-1, 'DATE']

    # 결과값 저장할 데이터프레임 생성
    home_split = pd.DataFrame()
    away_split = pd.DataFrame()

    while True:
        
        start_date = str(first_date)

        end_date = datetime.datetime.strptime(start_date, '%Y%m%d')
        end_date = end_date + datetime.timedelta(days=period)
        end_date = end_date.strftime('%Y%m%d')

        pred_date = datetime.datetime.strptime(end_date, '%Y%m%d')
        pred_date = pred_date + datetime.timedelta(days=24)
        pred_date = pred_date.strftime('%Y%m%d')

        if int(pred_date) >= last_date:
            print('가져오는 날짜{}가 마지막 날짜{} 이후의 데이터입니다.'.format(pred_date, last_date))
            break

        # 해당 시즌 타자 목록 (name -> pcode)
        hitter_list = list(set(df['PCODE']))

        # 더해줄 칼럼 목록 (avg, obp, slg, ops, avLI, RE24 제외)
        target_col = ['ab', 'score', 'hit', '2_hit', '3_hit', 'homerun', 'tb', 'rbi', 'sb', 'cs', 'bb', 'hpp', 'ibb', 'so', 'gdp', 'sh', 'sf', 'pitch', 'WPA', 'power_barrel', 'contact_barrel', 'clutch_barrel']

        # start_date 이후의 경기만 추출
        tr_df = df[ (df['DATE'] >= int(start_date)) & (df['DATE'] <= int(end_date)) ]
        ts_df = df[ (df['DATE'] > int(end_date)) & (df['DATE'] <= int(pred_date)) ]

        # first_date + interval
        first_date = datetime.datetime.strptime(start_date, '%Y%m%d')
        first_date = first_date + datetime.timedelta(days=interval)
        first_date = first_date.strftime('%Y%m%d')

        # 타자 한명씩 추출
        for player in hitter_list:

            tr_pl_data = tr_df[tr_df['PCODE'] == player]
            ts_pl_data = ts_df[ts_df['PCODE'] == player]

            away_tr = tr_pl_data[ tr_pl_data['vs'].str.contains('@') ]
            home_tr = tr_pl_data[ tr_pl_data['vs'].str.contains('@')  == False ]

            away_ts = ts_pl_data[ ts_pl_data['vs'].str.contains('@') ]
            home_ts = ts_pl_data[ ts_pl_data['vs'].str.contains('@')  == False ]

            if (len(away_tr) < del_cri) | (len(home_tr) < del_cri) | (len(away_ts) < 3.5) | (len(home_ts) < 3.5) :
                if except_print == True:
                    print('{}은/는 경기 수가 {}개보다 작기 때문에 삭제'.format(player, del_cri))
                continue

            else:

                # tr_data의 타겟 칼럼을 모두 합해서 저장
                home_sum = home_tr.loc[:, target_col].sum()
                away_sum = away_tr.loc[:, target_col].sum()
                # 어떤 선수인지 저장 (name -> pcode)
                home_sum['PCODE'] = player
                away_sum['PCODE'] = player

                home_sum['NAME'] = tr_pl_data.iloc[0,0]
                away_sum['NAME'] = tr_pl_data.iloc[0,0]

                # ts_data의 성적들로 avg, slg, obp, ops 라벨 생성
                home_ts_sum = home_ts.loc[:, target_col].sum()
                away_ts_sum = away_ts.loc[:, target_col].sum()

                home_sum['avg_label'] = home_ts_sum['hit'] / home_ts_sum['ab'] if home_ts_sum['ab'] != 0 else 0
                home_sum['slg_label'] = home_ts_sum['tb'] / home_ts_sum['ab'] if home_ts_sum['ab'] != 0 else 0
                home_sum['obp_label'] = (home_ts_sum['hit'] + home_ts_sum['bb'] + home_ts_sum['hpp']) / (home_ts_sum['ab'] +  home_ts_sum['bb'] + home_ts_sum['hpp'] + home_ts_sum['sf'])
                home_sum['ops_label'] = home_sum['slg_label'] + home_sum['obp_label']

                away_sum['avg_label'] = away_ts_sum['hit'] / away_ts_sum['ab'] if away_ts_sum['ab'] != 0 else 0
                away_sum['slg_label'] = away_ts_sum['tb'] / away_ts_sum['ab'] if away_ts_sum['ab'] != 0 else 0
                away_sum['obp_label'] = (away_ts_sum['hit'] + away_ts_sum['bb'] + away_ts_sum['hpp']) / (away_ts_sum['ab'] +  away_ts_sum['bb'] + away_ts_sum['hpp'] + away_ts_sum['sf'])
                away_sum['ops_label'] = away_sum['slg_label'] + away_sum['obp_label']

                # Series 데이터를 DataFrame 형식으로 변환
                home_result = home_sum.to_frame().transpose()
                away_result = away_sum.to_frame().transpose()
                    
                # 이 선수 데이터를 전체 데이터셋에 추가
                home_split = pd.concat([home_split, home_result])
                away_split = pd.concat([away_split, away_result])
            
    # 데이터셋 인덱스 초기화
    home_split = home_split.reset_index(drop=True)
    away_split = away_split.reset_index(drop=True)
            
    return home_split, away_split

In [170]:
home_2018, away_2018 = order(df = df_2018, period = 100, interval = 7, del_cri= 10, except_print = False)

가져오는 날짜20181018가 마지막 날짜20181014 이후의 데이터입니다.

In [171]:
home_2019, away_2019 = order(df = df_2019, period = 100, interval = 7, del_cri= 10, except_print = False)
home_2020, away_2020 = order(df = df_2020, period = 100, interval = 7, del_cri= 10, except_print = False)
home_2021, away_2021 = order(df = df_2021, period = 50, interval = 7, del_cri= 10, except_print = False)

가져오는 날짜20191003가 마지막 날짜20191001 이후의 데이터입니다.
가져오는 날짜20201101가 마지막 날짜20201031 이후의 데이터입니다.
가져오는 날짜20210714가 마지막 날짜20210711 이후의 데이터입니다.

In [172]:
print('홈 경기 row 개수\n2018 : {}, 2019 : {}, 2020 : {}, 2021 : {}'.format(home_2018.shape[0], home_2019.shape[0], home_2020.shape[0], home_2021.shape[0]))
print('원정 경기 row 개수\n2018 : {}, 2019 : {}, 2020 : {}, 2021 : {}'.format(away_2018.shape[0], away_2019.shape[0], away_2020.shape[0], away_2021.shape[0]))

홈 경기 row 개수
2018 : 765, 2019 : 708, 2020 : 727, 2021 : 264
원정 경기 row 개수
2018 : 765, 2019 : 708, 2020 : 727, 2021 : 264

In [191]:
def cal_feature(data):

    new_data = data.copy()

    new_data['avg'] = new_data.apply(lambda x: round(x['hit'] / x['ab'], 3) if x['ab'] != 0 else 0, axis=1)
    new_data['obp'] = new_data.apply(lambda x: round((x['hit'] + x['bb'] + x['hpp']) / (x['ab'] + x['bb'] + x['hpp'] + x['sf']), 3) if (x['ab'] + x['bb'] + x['hpp'] + x['sf']) != 0 else 0, axis=1)
    new_data['slg'] = new_data.apply(lambda x: round(x['tb'] / x['ab'], 3) if x['ab'] != 0 else 0, axis=1)
    new_data['ops'] = new_data['obp'] + new_data['slg']
    new_data['pa'] = new_data['ab'] + new_data['bb'] + new_data['sf']
    new_data['1_hit'] = new_data['hit'] - new_data['2_hit'] - new_data['3_hit'] - new_data['homerun']
    new_data['xh'] = new_data['2_hit'] + new_data['3_hit'] + new_data['homerun']


    new_data['babib'] = new_data.apply(lambda x: round((x['hit'] - x['homerun']) / (x['ab'] - x['so'] - x['homerun'] + x['sf']), 3) if (x['ab'] - x['so'] - x['homerun'] + x['sf']) != 0 else 0, axis=1)
    new_data['pitch/pa'] = new_data.apply(lambda x: round(x['pitch'] / x['pa'], 2) if x['pa'] != 0 else 0, axis=1)
    new_data['cq'] = new_data.apply(lambda x: round((0.5 * x['hit'] + 0.3 * x['tb']) / (x['ab'] - x['so']), 3) if (x['ab'] - x['so']) != 0 else 0, axis=1)
    new_data['b/k'] = new_data.apply(lambda x: round(x['bb'] / x['so'], 3) if x['so'] != 0 else 0, axis=1)
    new_data['IsoP'] = new_data['slg'] - new_data['avg']
    new_data['IsoD'] = new_data['obp'] - new_data['avg']
    new_data['psn'] = new_data.apply(lambda x: round((2 * x['homerun'] * x['sb']) / (x['homerun'] + x['sb']), 3) if (x['homerun'] + x['sb']) != 0 else 0, axis=1)
    new_data['hr%'] = new_data.apply(lambda x: round(x['homerun'] / x['pa'], 3) if x['pa'] != 0 else 0, axis=1)
    new_data['kk%'] = new_data.apply(lambda x: round(x['so'] / x['pa'], 3) if x['pa'] != 0 else 0, axis=1)
    new_data['bb%'] = new_data.apply(lambda x: round(x['bb'] / x['pa'], 3) if x['pa'] != 0 else 0, axis=1)
    new_data['xh/ab'] = new_data.apply(lambda x: round(x['xh'] / x['pa'], 3) if x['pa'] != 0 else 0, axis=1)
    new_data['xh/h'] = new_data.apply(lambda x: round(x['xh'] / x['hit'], 3) if x['hit'] != 0 else 0, axis=1)
    new_data['hr/xh'] = new_data.apply(lambda x: round(x['homerun'] / x['xh'], 3) if x['xh'] != 0 else 0, axis=1)
    new_data['pa/hr'] = new_data.apply(lambda x: round(x['pa'] / x['homerun'], 3) if x['homerun'] != 0 else 0, axis=1)
    new_data['ab/hr'] = new_data.apply(lambda x: round(x['ab'] / x['homerun'], 3) if x['homerun'] != 0 else 0, axis=1)
    new_data['ueqr'] = new_data.apply(lambda x: round((x['hit'] + x['tb'] + 1.5*(x['bb'] + x['hpp'] + x['sb']) + x['sh'] + x['sf'] - x['ibb']/2) / (x['ab'] + x['bb'] + x['hpp'] + x['sh'] + x['sf'] + x['cs'] + x['sb']), 3) if (x['ab'] + x['bb'] + x['hpp'] + x['sh'] + x['sf'] + x['cs'] + x['sb']) != 0 else 0, axis=1)
    new_data['wOBA'] = new_data.apply(lambda x: round((0.72 * x['bb'] + 0.75 * x['hpp'] + 0.9 * x['1_hit'] + 1.24 * x['2_hit'] + 1.56 * x['3_hit'] + 1.95 * x['homerun']) / (x['pa'] - x['ibb']), 3) if (x['pa'] - x['ibb']) != 0 else 0, axis=1)


    new_data['score'] = round((new_data['score'] / new_data['pa']).astype(float), 3)
    new_data['hit'] = round((new_data['hit'] / new_data['pa']).astype(float), 3)
    new_data['1_hit'] = round((new_data['1_hit'] / new_data['pa']).astype(float), 3)
    new_data['xh'] = round((new_data['xh'] / new_data['pa']).astype(float), 3)
    new_data['2_hit'] = round((new_data['2_hit'] / new_data['pa']).astype(float), 3)
    new_data['3_hit'] = round((new_data['3_hit'] / new_data['pa']).astype(float), 3)
    new_data['homerun'] = round((new_data['homerun'] / new_data['pa']).astype(float), 3)
    new_data['tb'] = round((new_data['tb'] / new_data['pa']).astype(float), 3)
    new_data['rbi'] = round((new_data['rbi'] / new_data['pa']).astype(float), 3)
    new_data['sb'] = round((new_data['sb'] / new_data['pa']).astype(float), 3)
    new_data['cs'] = round((new_data['cs'] / new_data['pa']).astype(float), 3)
    new_data['bb'] = round((new_data['bb'] / new_data['pa']).astype(float), 3)
    new_data['hpp'] = round((new_data['hpp'] / new_data['pa']).astype(float), 3)
    new_data['ibb'] = round((new_data['ibb'] / new_data['pa']).astype(float), 3)
    new_data['so'] = round((new_data['so'] / new_data['pa']).astype(float), 3)
    new_data['gdp'] = round((new_data['gdp'] / new_data['pa']).astype(float), 3)
    new_data['sh'] = round((new_data['sh'] / new_data['pa']).astype(float), 3)
    new_data['sf'] = round((new_data['sf'] / new_data['pa']).astype(float), 3)
    new_data['WPA'] = round((new_data['WPA'] / new_data['pa']).astype(float), 3)
    new_data['power_barrel'] = round((new_data['power_barrel'] / new_data['pa']).astype(float), 3)
    new_data['contact_barrel'] = round((new_data['contact_barrel'] / new_data['pa']).astype(float), 3)
    new_data['clutch_barrel'] = round((new_data['clutch_barrel'] / new_data['pa']).astype(float), 3)


    clean_col = ['PCODE', 'NAME', 'ab', 'pa', 'score', 'hit', '1_hit', '2_hit', '3_hit', 'homerun', 'xh', 'tb', 'rbi', 'sb', 'cs', 'bb', 'hpp', 'ibb', 'so', 'gdp', 'sh', 'sf', 'avg', 'obp', 'slg', 'ops', 'WPA', 'babib',
             'pitch/pa', 'cq', 'b/k', 'IsoP', 'IsoD', 'psn', 'hr%', 'kk%', 'bb%', 'xh/ab', 'xh/h', 'hr/xh', 'pa/hr','ab/hr', 'ueqr', 'wOBA', 'power_barrel', 'contact_barrel', 'clutch_barrel', 'avg_label', 'slg_label', 'obp_label', 'ops_label']

    new_data = new_data[clean_col]

    return new_data

In [192]:
home_df = [home_2018, home_2019, home_2020, home_2021]
away_df = [away_2018, away_2019, away_2020, away_2021]
years = [2018, 2019, 2020, 2021]

for i in range(4):

    globals()['final_home_{}'.format(years[i])] = cal_feature(home_df[i])
    globals()['final_away_{}'.format(years[i])] = cal_feature(away_df[i])

In [193]:
final_home_2018

     PCODE NAME   ab   pa  ...  avg_label  slg_label  obp_label  ops_label
0    76290  김현수  138  168  ...   0.342857   0.428571    0.44186   0.870432
1    76802  김성현   97  106  ...   0.291667   0.291667    0.46875   0.760417
2    64006  심우준   91   97  ...   0.230769   0.230769   0.285714   0.516484
3    76812  이재원   81   98  ...   0.310345   0.551724   0.411765   0.963489
4    71184  이성우   36   37  ...        0.2        0.4        0.2        0.6
..     ...  ...  ...  ...  ...        ...        ...        ...        ...
760  61404  김헌곤   96  108  ...   0.173913   0.217391       0.24   0.457391
761  99810  이진영   66   75  ...   0.409091   0.454545   0.409091   0.863636
762  62947  나성범  112  128  ...   0.304348   0.521739    0.37037    0.89211
763  74215  윤석민  100  110  ...   0.333333        0.5       0.36       0.86
764  76267  최주환  106  126  ...   0.354839   0.645161   0.411765    1.05693

[765 rows x 51 columns]

In [194]:
final_home_2018.to_csv('/content/drive/MyDrive/빅콘테스트/분석데이터/home_2018.csv')
final_home_2019.to_csv('/content/drive/MyDrive/빅콘테스트/분석데이터/home_2019.csv')
final_home_2020.to_csv('/content/drive/MyDrive/빅콘테스트/분석데이터/home_2020.csv')
final_home_2021.to_csv('/content/drive/MyDrive/빅콘테스트/분석데이터/home_2021.csv')

final_away_2018.to_csv('/content/drive/MyDrive/빅콘테스트/분석데이터/away_2018.csv')
final_away_2019.to_csv('/content/drive/MyDrive/빅콘테스트/분석데이터/away_2019.csv')
final_away_2020.to_csv('/content/drive/MyDrive/빅콘테스트/분석데이터/away_2020.csv')
final_away_2021.to_csv('/content/drive/MyDrive/빅콘테스트/분석데이터/away_2021.csv')