<a href="https://colab.research.google.com/github/KimGriezmann/Bigcontest_2021/blob/master/working_space_SeongGwan/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B3%91%ED%95%A9_%EC%8B%9C%EB%8F%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
def create_df():

  #연도별 데이터 경로
  HTS_dir = '/content/drive/MyDrive/빅콘테스트/01_제공데이터/2021 빅콘테스트_데이터분석분야_챔피언리그_스포츠테크_HTS'
  Crawl_dir = '/content/drive/MyDrive/빅콘테스트/01_제공데이터/data'

  year = [2018, 2019, 2020, 2021]

  for i in year:
    globals()['HTS_{}'.format(i)]     = pd.read_csv(HTS_dir + '_' + str(i) + '.csv', encoding='CP949')
    globals()['Crawl_{}'.format(i)]     = pd.read_csv(Crawl_dir + '_' + str(i) + '.csv', encoding='CP949')

create_df()

2018년 ~10.14

2019년 ~10.1

2020년 ~10.31

In [3]:
HTS_2020['DATE'] = HTS_2020['G_ID'].apply(lambda x: int(x[:8]))

In [4]:
HTS_2020

       GYEAR           G_ID         PIT_ID  ...  PIT_VEL STADIUM      DATE
0       2020  20200505HHSK0  200505_140454  ...   144.39      문학  20200505
1       2020  20200505HHSK0  200505_140623  ...   145.09      문학  20200505
2       2020  20200505HHSK0  200505_141146  ...   132.62      문학  20200505
3       2020  20200505HHSK0  200505_141334  ...   133.36      문학  20200505
4       2020  20200505HHSK0  200505_141409  ...   132.51      문학  20200505
...      ...            ...            ...  ...      ...     ...       ...
34497   2020  20201031NCHT0  201031_193901  ...   130.55      광주  20201031
34498   2020  20201031NCHT0  201031_194414  ...   147.02      광주  20201031
34499   2020  20201031NCHT0  201031_194827  ...   136.33      광주  20201031
34500   2020  20201031NCHT0  201031_200246  ...   144.03      광주  20201031
34501   2020  20201031NCHT0  201031_201522  ...   119.69      광주  20201031

[34502 rows x 12 columns]

In [5]:
Crawl_2020['DATE'] = Crawl_2020['day'].apply(lambda x: int(x.replace('-', '')))

In [6]:
Crawl_2020 = Crawl_2020[Crawl_2020['DATE'] <= 20201031].sort_values('DATE')

In [7]:
Crawl_2020

              day   vs inn pitcher batter  ...    REa   WPs   WPe    WPa      DATE
0      2020-05-05   삼성  1초     백정현    나성범  ...  0.134  53.8  52.6  0.012  20200505
41786  2020-05-05   NC  7말     임창민    박해민  ... -0.258   6.9   5.1 -0.018  20200505
41785  2020-05-05   NC  4말    루친스키    박해민  ... -0.251  27.3  24.5 -0.028  20200505
41784  2020-05-05   NC  2말    루친스키    박해민  ... -0.251  52.4  50.0 -0.024  20200505
41097  2020-05-05   KT  9초     하준호    정보근  ... -0.180   0.7   0.7 -0.001  20200505
...           ...  ...  ..     ...    ...  ...    ...   ...   ...    ...       ...
4945   2020-10-31  KIA  2초     임기영    김성욱  ... -0.322  49.8  52.7 -0.030  20201031
4946   2020-10-31  KIA  4초     임기영    김성욱  ... -0.258  26.7  28.5 -0.018  20201031
4947   2020-10-31  KIA  6초     임기영    김성욱  ...  0.134  72.5  70.5  0.021  20201031
33134  2020-10-31   NC  7말     김태경    유민상  ... -0.258  79.1  77.2 -0.019  20201031
34160  2020-10-31   NC  9말     박진우    한승택  ... -0.337  70.8  63.5 -0.073  20201031

[57666 rows x 15 columns]

일단 타구 맞춰놓고 생각해보자

In [12]:
# 타구맞음
except_list = ['삼진', '볼넷', '몸에', '고의', '실책', '낫아웃']

test_list = '|'.join(except_list)
Crawl_2020_new = Crawl_2020[Crawl_2020['result'].str.contains(test_list) == False].reset_index(drop=True)

In [13]:
Crawl_2020_new

              day   vs inn pitcher batter  ...    REa   WPs   WPe    WPa      DATE
0      2020-05-05   삼성  1초     백정현    나성범  ...  0.134  53.8  52.6  0.012  20200505
1      2020-05-05   NC  2말    루친스키    박해민  ... -0.251  52.4  50.0 -0.024  20200505
2      2020-05-05   KT  9초     하준호    정보근  ... -0.180   0.7   0.7 -0.001  20200505
3      2020-05-05   KT  7초     김재윤    정보근  ... -0.117  20.7  21.5 -0.008  20200505
4      2020-05-05   KT  3초   데스파이네    정보근  ... -0.180  64.0  65.9 -0.018  20200505
...           ...  ...  ..     ...    ...  ...    ...   ...   ...    ...       ...
40888  2020-10-31  KIA  2초     임기영    김성욱  ... -0.322  49.8  52.7 -0.030  20201031
40889  2020-10-31  KIA  4초     임기영    김성욱  ... -0.258  26.7  28.5 -0.018  20201031
40890  2020-10-31  KIA  6초     임기영    김성욱  ...  0.134  72.5  70.5  0.021  20201031
40891  2020-10-31   NC  7말     김태경    유민상  ... -0.258  79.1  77.2 -0.019  20201031
40892  2020-10-31   NC  9말     박진우    한승택  ... -0.337  70.8  63.5 -0.073  20201031

[40893 rows x 15 columns]

아예 똑같은게 두번 크롤링된게 있는듯?

In [71]:
Crawl_2020_new.drop_duplicates(keep='first', inplace=True, ignore_index=True)
Crawl_2020_new

              day   vs inn pitcher batter  ...    REa   WPs   WPe    WPa      DATE
0      2020-05-05   삼성  1초     백정현    나성범  ...  0.134  53.8  52.6  0.012  20200505
1      2020-05-05   NC  2말    루친스키    박해민  ... -0.251  52.4  50.0 -0.024  20200505
2      2020-05-05   KT  9초     하준호    정보근  ... -0.180   0.7   0.7 -0.001  20200505
3      2020-05-05   KT  7초     김재윤    정보근  ... -0.117  20.7  21.5 -0.008  20200505
4      2020-05-05   KT  3초   데스파이네    정보근  ... -0.180  64.0  65.9 -0.018  20200505
...           ...  ...  ..     ...    ...  ...    ...   ...   ...    ...       ...
40047  2020-10-31  KIA  2초     임기영    김성욱  ... -0.322  49.8  52.7 -0.030  20201031
40048  2020-10-31  KIA  4초     임기영    김성욱  ... -0.258  26.7  28.5 -0.018  20201031
40049  2020-10-31  KIA  6초     임기영    김성욱  ...  0.134  72.5  70.5  0.021  20201031
40050  2020-10-31   NC  7말     김태경    유민상  ... -0.258  79.1  77.2 -0.019  20201031
40051  2020-10-31   NC  9말     박진우    한승택  ... -0.337  70.8  63.5 -0.073  20201031

[40052 rows x 15 columns]

9월1일 롯데 vs kt 경기 분석

In [72]:
HTS_2020[(HTS_2020['G_ID'] == '20200901LTKT0') & (HTS_2020['T_ID'] == 'LT') & (HTS_2020['INN'] == 4)]

       GYEAR           G_ID         PIT_ID  ...  PIT_VEL STADIUM      DATE
22604   2020  20200901LTKT0  200901_194800  ...    127.5      수원  20200901

[1 rows x 12 columns]

In [73]:
Crawl_2020_new[ (Crawl_2020_new['DATE'] == 20200901) & (Crawl_2020_new['inn'] == '4초') & (Crawl_2020_new['vs'] == 'KT')]

              day  vs inn pitcher batter  ...    REa   WPs   WPe    WPa      DATE
26391  2020-09-01  KT  4초     배제성    한동희  ...  0.398  88.0  85.1  0.030  20200901
26516  2020-09-01  KT  4초     배제성    안치홍  ... -1.573  80.1  91.5 -0.114  20200901

[2 rows x 15 columns]

In [74]:
HTS_2020[(HTS_2020['G_ID'] == '20200901LTKT0') & (HTS_2020['T_ID'] == 'LT') & (HTS_2020['INN'] == 9)]

       GYEAR           G_ID         PIT_ID  ...  PIT_VEL STADIUM      DATE
22635   2020  20200901LTKT0  200901_213245  ...   140.42      수원  20200901

[1 rows x 12 columns]

In [75]:
Crawl_2020_new[ (Crawl_2020_new['DATE'] == 20200901) & (Crawl_2020_new['inn'] == '9초') & (Crawl_2020_new['vs'] == 'KT')]

              day  vs inn pitcher batter  ...    REa    WPs    WPe  WPa      DATE
26463  2020-09-01  KT  9초     이상동    이병규  ... -0.573  100.0  100.0 -0.0  20200901
26490  2020-09-01  KT  9초     이상동    마차도  ... -0.258  100.0  100.0 -0.0  20200901

[2 rows x 15 columns]

발사각도가 너무 낮은게 측정이 안된건가?

In [76]:
Crawl_2020_new[Crawl_2020_new['result'].str.contains('뜬공|플라이')].shape

(12826, 15)

In [77]:
Crawl_2020_new[Crawl_2020_new['result'].str.contains('땅볼|병살타|삼중살|번트')].shape

(12870, 15)

근데 홈런 개수도 다르던데?

In [78]:
tmp1 = Crawl_2020_new[Crawl_2020_new['result'].str.contains('홈런')]['DATE'].reset_index(drop=True)
tmp2 = HTS_2020[HTS_2020['HIT_RESULT'] == '홈런']['DATE'].reset_index(drop=True)

In [79]:
len(tmp1), len(tmp2)

(1362, 1359)

In [85]:
for i in range(513,1359):
    if pd.Series(sorted(tmp1))[i] != pd.Series(sorted(tmp2))[i]:
        print(i, pd.Series(sorted(tmp1))[i])
        break

520 20200707

In [81]:
tmp = Crawl_2020_new[Crawl_2020_new['result'].str.contains('홈런')]
tmp[tmp['DATE'] == 20200705]

              day   vs inn pitcher batter  ...    REa   WPs   WPe    WPa      DATE
14346  2020-07-05   NC  9초     원종현    나주환  ...  2.054   5.0   0.7  0.044  20200705
14376  2020-07-05   키움  2말     이승호    박경수  ...  1.982  64.5  82.5  0.180  20200705
14408  2020-07-05   KT  5초     김민수    박병호  ...  1.724  96.3  91.7  0.047  20200705
14439  2020-07-05  KIA  9말     문경찬    김태진  ...  1.724  10.6  58.0  0.474  20200705
14459  2020-07-05   롯데  2초     박세웅    최준우  ...  1.724  69.8  52.4  0.175  20200705
14462  2020-07-05  KIA  9말     전상현    박석민  ...  1.982   3.8   9.1  0.054  20200705
14465  2020-07-05   키움  8말     신재영    배정대  ...  1.724  98.9  99.8  0.009  20200705
14488  2020-07-05   삼성  8초     장지훈    김현수  ...  3.302  23.4   2.0  0.215  20200705
14519  2020-07-05   한화  4말     채드벨    박건우  ...  1.000  21.1  30.6  0.095  20200705
14594  2020-07-05   롯데  3초     박세웅     최정  ...  1.000  54.3  42.3  0.120  20200705
14613  2020-07-05   LG  2말     정찬헌    강민호  ...  1.773  53.4  72.3  0.189  20200705

[11 rows x 15 columns]

In [82]:
tmp = HTS_2020[HTS_2020['HIT_RESULT'] == '홈런']
tmp[tmp['DATE'] == 20200705]

       GYEAR           G_ID         PIT_ID  ...  PIT_VEL STADIUM      DATE
12342   2020  20200705HHOB0  200705_180328  ...   145.27      잠실  20200705
12413   2020  20200705HTNC0  200705_193054  ...   134.09      창원  20200705
12417   2020  20200705HTNC0  200705_194455  ...   133.23      창원  20200705
12419   2020  20200705HTNC0  200705_195509  ...   127.47      창원  20200705
12432   2020  20200705LGSS0  200705_174007  ...   138.45      대구  20200705
12460   2020  20200705LGSS0  200705_195237  ...   145.05      대구  20200705
12484   2020  20200705WOKT0  200705_173255  ...   135.13      수원  20200705
12501   2020  20200705WOKT0  200705_184233  ...   123.17      수원  20200705
12518   2020  20200705WOKT0  200705_195852  ...   132.18      수원  20200705

[9 rows x 12 columns]